# PATH=/home/marina/anaconda3/envs/dynamic-risk-assessment/bin
# * * * * * python /home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py >> /home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/cronLog.txt 2>&1

Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
Traceback (most recent call last):
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/fullprocess.py", line 20, in <module>
    from ingestion import merge_multiple_dataframe
  File "/home/marina/Desktop/Coding/udacity/dynamic-risk-assesment-system/ingestion.py", line 17, in <module>
    with open("config.json", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
